### PR TITLE
add contribution guide

### LINKED ISSUE #53: add contribution readme
This will create a guide on setup the project and how to contribute towards it

### PR DESCRIPTION
**Pull request by okothkongo**
fixes #53

### CODE REVIEW

**Comment by fhunleth** [comment]
Thanks! I think this is a great start. I want to adjust some things, but I like the direction overall. Let me connect with you on Slack on a plan.

**Comment by fhunleth** [comment]
@okothkongo Do you have an editor that does Markdown validation? I use VSCode and the markdownlint plugin. I didn't see any spelling errors, but while you're at it, I also have "Code Spell Checker" installed and that is normally helpful.

The other thing I do with text files is word wrap them to 80 columns. I know that there are many opinions out there on this, but I really like how it looks when I read files in the shell. I use vim to wrap text (e.g., `gqj` to wrap the line you're on). I'm not sure how to do it in VSCode, but I'm sure there's a good way there as well.

**Comment by okothkongo** [comment]
@fhunleth thank your suggestions with regards to plugins and word-wrap I have put them into consideration in the lastest commit

**Comment by fhunleth** [comment]
Closing for now due to conflicts and other discussion. Agree that something like this is needed.

**Pull request closed without merging**
